basic/config/urls.py
from django.contrib import admin
from django.urls import path, include
from support.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('support/',include('support.urls', namespace='support')),
]

basic/support/urls.py
from django.urls import path
from support.views import support_list_view, support_detail_view

app_name='support'

urlpatterns = [
    path('',support_list_view, name='support-list'),
    path('<int:id>/', support_detail_view),
]

basic/support/models.py
from django.db import models

# Create your models here.
class Faq(models.Model):
    question = models.TextField(verbose_name='질문')
    QUES_CATEGORY = (
        (1, '일반'),
        (2, '계정'),
        (3, '기타'),
    )
    ques_category = models.IntegerField(choices=QUES_CATEGORY)
    answer = models.TextField( verbose_name='답변')
    writer = models.CharField(max_length=7, null=True, blank=True, verbose_name='작성자')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='작성일')
    last_updater = models.CharField(max_length=7, null=True, blank=True, verbose_name='최종 수정자')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='최종 수정일')

basic/support/views.py
from django.shortcuts import render
from .models import Faq

# Create your views here.
def index(request):
    return render(request, 'index.html')

def support_list_view(request):
    faq_list = Faq.objects.all().order_by('id')
    return render(request, 'support/support_list.html', {'faq_list' : faq_list} )
    
def support_detail_view(request,id):
    faq_detail = Faq.objects.get(id=id)
    print(faq_detail)
    return render(request, 'support/support_detail.html', {'faq_detail' : faq_detail})

basic/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    </script>
</head>
<body>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

basic/templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block content%}
<h1>Index화면</h1>
    
<ul>
    <li><a href="{% url 'support:support-list' %}">FAQ 목록</a></li>
</ul>
{% endblock %}

basic/templates/support/support_detail.html
{% extends 'base.html' %}
{% block title %}FAQ{% endblock %}

{% block content%}
<h2>FAQ 상세보기</h2>
<div>
    <from>
        <table style="font-size:14px; width:600px">
            <tr>
                <td style="width:60px">유형</td>
                <td>{{ faq_detail.get_ques_category_display }}</td>
            </tr>
            <tr>
                <td>작성자</td>
                <td>{{ faq_detail.writer }} | {{ faq_detail.created_at|date:"Y-m-d H:i:s" }}</td> 
            </tr>
            <tr>
                <td>질문</td>
                <td><textarea style="width : 60%; height: 100px" readonly>{{ faq_detail.question }}</textarea></td>
            </tr>
        </table>
    </from>
</div>
<hr style="margin-left:0; width:450px"/>
<div>
    <from>
        <table style="font-size:14px; width:600px"> 
            <tr>
                <td>답변자</td>
                <td>{{ faq_detail.last_updater }} | {{ faq_detail.updated_at|date:"Y-m-d H:i:s" }}</td>
            </tr>
            <tr>
                <td style="width:60px">답변</td>
                <td><textarea style="width : 60%; height: 100px" readonly>{{ faq_detail.answer }}</textarea></td>
            </tr>
        </table>
    </from>
</div>
<button onClick="history.back()" style="margin-left : 190px;">돌아가기</button>

{% endblock %} 

basic/templates/support/support_list.html
{% extends 'base.html' %}
{% block title %}FAQ{% endblock %}

{% block content%}
<h2>FAQ</h2>
<table>
    <tr>
        <th style="width: 50px; border-bottom: 1px solid;">NO</th>
        <th style="text-align:center; width: 550px; border-bottom: 1px solid;" >질문</th>
    </tr>
    {% for faq in faq_list %}
    <tr>
        <td style="text-align:center;">{{ faq.id }}</td>
        <td style="font-size:14px;"><a href="{{ faq.id }}" style="text-decoration:none; color: black;">{{ faq.question }}</a></td>
    </tr>
    {% endfor %}
</tabel>
{% endblock %}